import type { Metadata } from "next";
import * as f from "@/fonts";
import "./globals.scss";

export const metadata: Metadata = {
  title: "HNG 11 Apology Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${f.poppins.className} ${f.raleway.variable} ${f.workSans.variable} ${f.unica} bg-primary text-purple-50 container`}
      >
        {children}
      </body>
    </html>
  );
}
